### ISSUE TITLE
小驼峰

### ISSUE THREAD

**Issue by FutureXiang** [OO-guide-2019/codestyle-guide#1]
>###  `^[a-z]([a-z0-9][a-zA-Z0-9]*)?$`

Seriously?

**为啥不让用aBox、aManager这种命名呢……**（不是很自然吗

甚至IDE都给这样的提示
![default](https://user-images.githubusercontent.com/33350017/53088015-890e2f80-3543-11e9-9984-fb19ede7b7bc.png)

望稍稍松绑……（有道理的话

**Comment by HansBug** [comment]
emmm这个问题个人感觉似乎确实可以，不过我之前也确实没见过有人用a开头的命名方式（当然也可能是我孤陋寡闻）
以及，刚才去翻看了一下Google官方的代码风格指南以及Google提供的checkstyle配置文件（也就是我们所参照的原版），发现配置确实如此：
* 配置文件原文：https://github.com/checkstyle/checkstyle/blob/88907c5e43cf9842ac9ba742fb46a951e2c10a4f/src/main/resources/google_checks.xml#L148
* 关于小驼峰：
https://google.github.io/styleguide/javaguide.html#s5.3-camel-case

所以个人还是觉得这件事还是按照Google官方原版配置来走吧，毕竟人家一直这样设置总该有他们的道理。
