### ISSUE TITLE
[Checkstyle规则]有关布尔表达式复杂度的问题

### ISSUE THREAD

**Issue by YuxuanChen98** [OO-guide-2019/codestyle-guide#2]
checkstyle中有规定布尔表达式&& ||等逻辑运算符不能超过6个。
我的代码中一个布尔表达式里有超过6个逻辑运算符，但是checkstyle没有发现异常，请问这个我的这个表达式是合法的吗？是不是如果checkstyle没有报错就不会有问题？

**Comment by PaParaZz1** [comment]
不好意思咕咕了几天。。。。
配置文件中确实是规定不超过6个，可以把你的代码贴一下吗，我们详细进行确认。谢谢！

**Comment by YuxuanChen98** [comment]
没关系
我刚刚把之前的代码复现了一遍，checkstyle又能够检测出问题了，可能是有间歇性抽风的情况，建议别的同学写完代码之后关闭IDE 再打开 多次检查，以免出现问题
